### ISSUE TITLE
Simdx86 project

### ISSUE THREAD

**Issue by rcaridade145** [jpd002/Play--CodeGen#21]
Hello.
I used this project - https://sourceforge.net/p/simdx86/code/HEAD/tree/src/ - a while back on  a project of mine. It hasn't been developed in a while, but perhaps it may hold some value for you and Play! .

Thank you for your work.

**Comment by jpd002** [comment]
Hi!

This seems to be a 3D math library, which won't be of much use for the emulator since it doesn't do any 3D math directly. Games do, but the emulator has no knowledge of what the games are trying to do: it just processes projected 2D triangles. Also, the JIT already uses SIMD instructions when possible.

Thanks for the suggestion nonetheless!
